port: 7890
socks-port: 7891
mode: rule
ipv6: true
proxies:
  - name: "SOCKS"
    type: socks5
    server: 10.128.36.223
    port: 1080
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - SOCKS
      - DIRECT
rules:
  - GEOIP,CN,DIRECT
  - MATCH,PROXY